### ISSUE TITLE
Comparison of logging level debug and logging level Error

### ISSUE THREAD

**Issue by shreyas-girjapure** [shreyas-girjapure/apex-logging#9]

**Comment by shreyas-girjapure** [comment]
Screenshots and sample codes are expected at the end of result

**Comment by Mehul-Suryavanshi** [comment]
**Actions Performed** - Ran a script which logged msg using 1. system.debug('Hello'); and 2. system.debug(logginglevel.ERROR,'Hello'); over an iteration of 10000.

**Observations** - In first scenario, i.e. for logging level DEBUG, system took 1.273 secs to process the entire operation, but for second scenario, i.e. for logging level ERROR, system took almost half the time than previous operation, which was about 0.669 secs.

**Conclusion** - The use of logging level DEBUG must be avoided on production package. And in case we intend to use debug statements, then we must keep logging level as ERROR so as to reduce CPU time.

PFA Logs for both Scenarios
[LoggingLevel_ERROR.log](https://github.com/shreyas-girjapure/apex-logging/files/8948822/LoggingLevel_ERROR.log)
[LoggingLevel_DEBUG.log](https://github.com/shreyas-girjapure/apex-logging/files/8948825/LoggingLevel_DEBUG.log)
